# Generated by Django 4.0.6 on 2022-07-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('uid', models.PositiveIntegerField()),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other'), (3, 'Do not wish to answer')])),
                ('qualification', models.TextField(max_length=512)),
                ('specialization', models.TextField(max_length=512)),
                ('years_of_experience', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='generaluser',
            name='uid',
            field=models.PositiveIntegerField(default=1000000009),
            preserve_default=False,
        ),
    ]
