# Generated by Django 4.0.6 on 2022-07-18 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_doctor_id_remove_generaluser_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landing.doctor')),
                ('guser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landing.generaluser')),
            ],
        ),
    ]
