# Generated by Django 4.0.6 on 2022-07-18 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.doctor'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.generaluser'),
        ),
    ]
