# Generated by Django 4.0.6 on 2022-07-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_reservation_doctor_alter_reservation_guser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
